name=ACNode
version=2.0.6
author=dirkx
maintainer=Dirk-Willem van Gulik <dirkx-remove-this-2026@webweaving.org>
sentence=Access Control node for the Makerspace in Leiden,NL
paragraph=Software for access nodes that manage doors, machines and payments. Generally based on an ESP32, PoE ethernet, an OLED screenm contains RFID reader various I/O. See https://wiki.makerspaceleiden.nl/mediawiki/index.php/PowerNode_White for more information. The hardware can be found at https://oshwlab.com/dirkx/msl-node-4g-107
category=Other
url=https://github.com/MakerSpaceLeiden/ACNode
architectures=esp32
depends=Adafruit AW9523 (>=1.0.5), Adafruit BusIO (>=1.17.4), ArduinoJson (>=7.4.3), ESP Async WebServer (>=3.12.0), Async TCP (>=3.5.0), TLog (>=1.0.8), Adafruit GFX Library (>=1.12.6), Adafruit SH110X (>=2.1.15), PubSubClient (>=2.8), MFRC522-spi-i2c-uart-async (>=1.5.1)

